# Generated by Django 2.2.6 on 2019-11-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
